const MAX_SELECTED_MOVIES = 20;
const SOCIAL_BUTTON_SIZE = "32px";
const LOCALES = {
  ENGLISH: "en-us",
  UKRAINIAN: "uk",
};
const STORAGE_KEY = "locale";

export { MAX_SELECTED_MOVIES, SOCIAL_BUTTON_SIZE, LOCALES, STORAGE_KEY };
